## Workflow GitHub Actions pour vérifier le style de code PHP avec PHP CS Fixer
name: PHP CS Fixer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# 'on' définit les événements qui déclenchent le workflow : ici push et pull request sur la branche main

jobs:
  fix:
    runs-on: ubuntu-latest
    # 'runs-on' indique l'environnement d'exécution : ici un serveur Ubuntu

    steps:
      # Récupérer le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v2
        # 'uses' ici utilise l'action officielle GitHub pour cloner ton dépôt dans l'environnement d'exécution

      # Installer PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
        # 'uses' installe PHP 8.3 dans l'environnement. Aucune extension spécifique n'est nécessaire pour PHP CS Fixer

      # Installer les dépendances du projet via Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        # 'run' exécute une commande shell pour installer les dépendances PHP définies dans composer.json
        # Les options accélèrent l'installation et évitent les suggestions

       # Corriger les permissions sur PHPUnit 
      - name: Fix PHPUnit permissions
        run: chmod +x ./vendor/bin/phpunit 

      # Exécuter PHPStan pour analyser le code
      - name: Run tests
        run : vendor/bin/phpunit
