## Workflow GitHub Actions pour analyser le code avec PHPStan
name: PHPStan Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# 'on' définit les événements qui déclenchent le workflow : ici push et pull request sur la branche main

jobs:
  phpstan:
    runs-on: ubuntu-latest
    # 'runs-on' indique l'environnement d'exécution : ici un serveur Ubuntu

    steps:
      # Étape 1 : récupérer le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v2
        # 'uses' ici utilise l'action officielle GitHub pour cloner ton dépôt dans l'environnement d'exécution

      # Étape 2 : installer PHP avec les extensions nécessaires
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring
        # 'uses' ici installe PHP 8.3 avec l'extension mbstring, nécessaire pour PHPStan et d'autres scripts PHP

      # Étape 3 : installer les dépendances du projet via Composer
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        # 'run' exécute une commande shell pour installer toutes les bibliothèques définies dans composer.json
        # Les options évitent les suggestions et accélèrent l'installation

      # Étape 4 : exécuter PHPStan pour analyser le code
      - name: Run PHPStan
        run: composer run stan-check
        # 'run' ici lance le script 'stan-check' défini dans composer.json, qui exécute PHPStan pour détecter les erreurs ou problèmes de code
