## Workflow GitHub Actions pour analyser le code avec PHPStan
name: PHPStan Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# 'on' définit les événements qui déclenchent le workflow : ici push et pull request sur la branche main

jobs:
  phpstan:
    runs-on: ubuntu-latest
    # 'runs-on' indique l'environnement d'exécution : ici un serveur Ubuntu

    steps:
      # Récupérer le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v2
        # 'uses' ici utilise l'action officielle GitHub pour cloner ton dépôt dans l'environnement d'exécution

      # Installer PHP avec les extensions nécessaires
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring
        # 'uses' ici installe PHP 8.3 avec l'extension mbstring, nécessaire pour PHPStan et d'autres scripts PHP

      # Installer les dépendances du projet via Composer
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist
        # 'run' exécute une commande shell pour installer toutes les bibliothèques définies dans composer.json
        # Les options évitent les suggestions et accélèrent l'installation


      # Corriger les permissions sur PHPStan
      - name: Fix PHPStan permissions
        run: chmod +x ./vendor/bin/phpstan

      # Exécuter PHPStan pour analyser le code
      - name: Run tests
        run : vendor/bin/phpstan
