name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Récupérer le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # Installer PHP avec les extensions nécessaires
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo, xml, curl, zip
          coverage: none

      # Vérifier la version de PHP et Composer (utile pour debug)
      - name: Check PHP version
        run: php -v

      - name: Check Composer version
        run: composer -V

      # Installer les dépendances PHP via Composer
      - name: Install dependencies
        run: |
          composer install --no-progress --no-interaction --prefer-dist

      # Corriger les permissions sur PHPUnit (important !)
      - name: Fix PHPUnit permissions
        run: chmod +x ./vendor/bin/phpunit

      # Lancer les tests unitaires avec PHPUnit
      - name: Run tests
        run: vendor/bin/phpunit
